import { useEffect, useState } from "react";
import { getAssets, getMoments, saveMoments } from "./api";

// Scoped to editing ONE moment, opened by clicking its chip in
// ActiveSceneBar. Unlike titles (#32 — no shared id, text-matched), a
// moment scene's merged id ("scene-moment-{N}") is generated by
// merge_moment_scenes as exactly the array index of moments.json's
// proposals list (see generate_moments.py's merge_moment_scenes:
// `for index, proposal in enumerate(proposals)`), so the correlation
// here is exact, not a heuristic.
function momentIndexFromSceneId(sceneId: string): number | null {
    const match = /^scene-moment-(\d+)$/.exec(sceneId);
    return match ? Number(match[1]) : null;
}

interface Asset {
    id: string;
    caption: string;
}

const VALID_TERM_LEVELS = ["muted", "primary", "accent"] as const;

// Treatments whose content doesn't live in m.text and has no per-field
// editor yet get a read-only summary — matches ui/static/app.js's
// NO_TEXT_EDIT_TREATMENTS (side-terms and side-text/sideTextStyle got
// real editors, side-diagram/side-code/comparison have not yet).
const NO_TEXT_EDIT_TREATMENTS = new Set(["side-diagram", "side-code", "comparison"]);

function summarizeMomentContent(m: any): string {
    if (m.treatment === "comparison" && m.comparison) {
        return `${m.comparison.left || "?"} vs ${m.comparison.right || "?"}`;
    }
    if (m.treatment === "side-diagram" && m.diagram) {
        return (m.diagram.nodes || []).map((n: any) => n.label).join(" → ");
    }
    if (m.treatment === "side-code") {
        return m.codeAssetId || "";
    }
    return "";
}

interface Props {
    episodePath: string;
    sceneId: string;
    onClose: () => void;
}

export function MomentEditorPanel({ episodePath, sceneId, onClose }: Props) {
    const [moments, setMoments] = useState<any[] | null>(null);
    const [assetOptions, setAssetOptions] = useState<Asset[]>([]);
    const [status, setStatus] = useState("");
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        getMoments(episodePath)
            .then((data) => setMoments(data.moments ?? []))
            .catch(() => setMoments([]));
        getAssets(episodePath)
            .then(setAssetOptions)
            .catch(() => setAssetOptions([]));
    }, [episodePath]);

    if (!moments) return null;

    const index = momentIndexFromSceneId(sceneId);

    if (index === null || !moments[index]) {
        return (
            <div style={styles.wrap}>
                <div style={styles.header}>
                    <span>Moment</span>
                    <button className="secondary small" onClick={onClose}>
                        Close
                    </button>
                </div>
                <p style={styles.hint}>Couldn't find a matching entry in moments.json for this scene.</p>
            </div>
        );
    }

    const moment = moments[index];

    const update = (patch: Record<string, unknown>) => {
        setMoments((prev) => (prev ? prev.map((m, i) => (i === index ? { ...m, ...patch } : m)) : prev));
    };

    const updateTerm = (termIndex: number, patch: Record<string, unknown>) => {
        const terms = (moment.terms || []).map((t: any, ti: number) =>
            ti === termIndex ? { ...t, ...patch } : t
        );
        update({ terms });
    };

    const remove = async () => {
        const next = moments.filter((_, i) => i !== index);
        setStatus("Saving…");
        setError(null);
        try {
            await saveMoments(episodePath, next);
            setStatus("Removed.");
            onClose();
        } catch (e) {
            setError(String(e));
        }
    };

    const handleSave = async () => {
        setStatus("Saving…");
        setError(null);
        try {
            await saveMoments(episodePath, moments);
            setStatus("Saved — the next render will pick this up.");
        } catch (e) {
            setError(String(e));
        }
    };

    return (
        <div style={styles.wrap}>
            <div style={styles.header}>
                <span>{moment.treatment.toUpperCase()}</span>
                <button className="secondary small" onClick={onClose}>
                    Close
                </button>
            </div>

            {moment.treatment === "side-image" && (
                <select
                    value={moment.assetId ?? ""}
                    onChange={(e) => {
                        const asset = assetOptions.find((a) => a.id === e.target.value);
                        update({ assetId: e.target.value, caption: asset ? asset.caption : moment.caption });
                    }}
                    style={styles.input}
                >
                    {assetOptions.map((a) => (
                        <option key={a.id} value={a.id}>
                            {a.id} — {a.caption || ""}
                        </option>
                    ))}
                </select>
            )}

            {moment.treatment === "side-terms" && (
                <div style={styles.termsList}>
                    {(moment.terms || []).map((t: any, ti: number) => (
                        <div key={ti} style={styles.termRow}>
                            <input
                                type="text"
                                value={t.text || ""}
                                onChange={(e) => updateTerm(ti, { text: e.target.value })}
                                style={styles.termInput}
                            />
                            <select
                                value={t.level}
                                onChange={(e) => updateTerm(ti, { level: e.target.value })}
                                style={styles.termSelect}
                            >
                                {VALID_TERM_LEVELS.map((level) => (
                                    <option key={level} value={level}>
                                        {level}
                                    </option>
                                ))}
                            </select>
                        </div>
                    ))}
                </div>
            )}

            {NO_TEXT_EDIT_TREATMENTS.has(moment.treatment) && (
                <span style={styles.readonly}>{summarizeMomentContent(moment)}</span>
            )}

            {!["side-image", "side-terms"].includes(moment.treatment) &&
                !NO_TEXT_EDIT_TREATMENTS.has(moment.treatment) && (
                    <input
                        type="text"
                        value={moment.text || ""}
                        onChange={(e) => update({ text: e.target.value })}
                        style={styles.input}
                    />
                )}

            {moment.treatment === "side-text" && (
                <select
                    value={moment.sideTextStyle || "quote"}
                    onChange={(e) => update({ sideTextStyle: e.target.value })}
                    style={styles.input}
                >
                    <option value="quote">quote</option>
                    <option value="title">title</option>
                </select>
            )}

            {moment.reason && <p style={styles.reason}>{moment.reason}</p>}

            <div style={styles.actions}>
                <button onClick={handleSave}>Save changes</button>
                <button className="secondary" onClick={remove}>
                    Remove
                </button>
                <span style={styles.status}>{status}</span>
                {error && <span style={styles.error}>{error}</span>}
            </div>
        </div>
    );
}

const styles: Record<string, React.CSSProperties> = {
    wrap: {
        display: "flex",
        flexDirection: "column",
        gap: 8,
        padding: "12px 14px",
        background: "#161d24",
        border: "1px solid #2a333d",
        borderRadius: 8,
    },
    header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        fontSize: 12,
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: 0.5,
        color: "#9aa7b4",
    },
    hint: {
        fontSize: 12,
        color: "#9aa7b4",
        margin: 0,
    },
    input: {
        padding: "8px 12px",
        background: "#0b0f14",
        border: "1px solid #2a333d",
        borderRadius: 6,
        color: "#e8edf2",
        fontSize: 14,
    },
    termsList: {
        display: "flex",
        flexDirection: "column",
        gap: 6,
    },
    termRow: {
        display: "flex",
        gap: 6,
    },
    termInput: {
        flex: 1,
        padding: "6px 10px",
        background: "#0b0f14",
        border: "1px solid #2a333d",
        borderRadius: 6,
        color: "#e8edf2",
        fontSize: 13,
    },
    termSelect: {
        padding: "6px 10px",
        background: "#0b0f14",
        border: "1px solid #2a333d",
        borderRadius: 6,
        color: "#e8edf2",
        fontSize: 13,
    },
    readonly: {
        fontSize: 13,
        color: "#9aa7b4",
        fontStyle: "italic",
    },
    reason: {
        fontSize: 12,
        color: "#6b7683",
        margin: 0,
    },
    actions: {
        display: "flex",
        alignItems: "center",
        gap: 10,
    },
    status: {
        fontSize: 12,
        color: "#9aa7b4",
    },
    error: {
        fontSize: 12,
        color: "#ff8f8f",
    },
};
